### ISSUE TITLE
각자 깃허브 후기 작성

### ISSUE THREAD

**Issue by weeareteam** [weeareteam/oss_report#11]
ppt 만들어야 하는데 각자 후기 좀 작성해주세요~~~~

![image](https://user-images.githubusercontent.com/114068529/202732924-5167b2d8-b3fe-4624-b048-d461d041b802.png)

**Comment by amlslt** [comment]
김호민 후기: 깃허브를 처음 사용해봤을땐 불편하다고 생각한 부분이 많았는데 수업과 과제를통해 깃허브를 계속사용하다보니 어떤부분이 좋은지 잘 알 수있었고, 앞으로도 유용하게 사용할 수 있을것 같다고 느꼈습니다.

**Comment by nyryngji** [comment]
권민정 후기 :  수업을 듣기 전에는 깃허브를 어떻게 사용할지 막막하였으나 수업을 듣고 난 후에는 어떻게 활용해야할지에 대해 
                       대략적인 방향을 잡을 수 있었습니다.  또한 팀 활동을 통해 서로 상호작용하며 돕는 것이 매우 중요하다는 것을 알게 
                       되었습니다.

**Comment by yang9098** [comment]
양희민 후기 : 이 활동을 하면서 깃허브의 사용법을 더욱더 자세히 살펴보고 복습을 할 수 있는 계기가 되었습니다. 그리고 또한 팀활동을 하면서 학과사람들과의 유대를 키울수 있는 계기가 되었고, 서로 돕고 도움을 받으면서 많은 것을 배울 수 있었습니다.
